#!/bin/tcsh
#MSUB -l walltime=1:00:00
#MSUB -l nodes=2:ppn=2
#MSUB -N Rogers
#MSUB -j oe
#MSUB -o outfile
#MSUB -m abe


# Now run the script as this group - so all data files will belong

#  Shell commands
date
echo '*** Staring Parallel Job ***'
module load gcc
module load openmpi
module load friendly-testing
module load hdf5-parallel/1.8.13

setenv OMP_NUM_THREADS 8
#mpirun -np 2048 --mca mpi_paffinity_alone 0 ./sforce_free_mpert.cxx.op -tpp=2 restart restart1/restart >& outfile2
#mpirun -np 2048 --mca mpi_paffinity_alone 0 ./sigma.cxx.op -tpp=2
mpirun -np 4 -bysocket -bind-to-socket ./test_particle

# restart restart0/restart
date
echo '*** All Done ***'
# 
